language: cpp
dist: trusty

branches:
  only:
  - master

script: 
  # run cppcheck
  # 4 threads
  # ignore errors on external/**
  - cppcheck -j 4 --language=c++ --platform=win64 --suppress='*:external/**' --error-exitcode=1 --project=ScrapEngine/ScrapEngine.sln