language: cpp
dist: trusty

branches:
  only:
  - master

script: 
  # run cppcheck
  # 4 threads
  # ignore errors on external/**
  # do not use .sln to avoid to scan all import files of third party stuff
  - cppcheck -j 4 --language=c++ --platform=win64 --suppress='*:external/*' --error-exitcode=1 ./ScrapEngine/ScrapEngine/Engine/**