#pragma once

#include <Windows.h>
#include <GLFW/glfw3.h>

#define KEYBOARD_KEY_SPACE GLFW_KEY_SPACE

#define KEYBOARD_KEY_0 GLFW_KEY_0
#define KEYBOARD_KEY_1 GLFW_KEY_1
#define KEYBOARD_KEY_2 GLFW_KEY_2
#define KEYBOARD_KEY_3 GLFW_KEY_3
#define KEYBOARD_KEY_4 GLFW_KEY_4
#define KEYBOARD_KEY_5 GLFW_KEY_5
#define KEYBOARD_KEY_6 GLFW_KEY_6
#define KEYBOARD_KEY_7 GLFW_KEY_7
#define KEYBOARD_KEY_8 GLFW_KEY_8
#define KEYBOARD_KEY_9 GLFW_KEY_9

#define KEYBOARD_KEY_A GLFW_KEY_A
#define KEYBOARD_KEY_B GLFW_KEY_B
#define KEYBOARD_KEY_C GLFW_KEY_C
#define KEYBOARD_KEY_D GLFW_KEY_D
#define KEYBOARD_KEY_E GLFW_KEY_E
#define KEYBOARD_KEY_F GLFW_KEY_F
#define KEYBOARD_KEY_G GLFW_KEY_G
#define KEYBOARD_KEY_H GLFW_KEY_H
#define KEYBOARD_KEY_I GLFW_KEY_I
#define KEYBOARD_KEY_J GLFW_KEY_J
#define KEYBOARD_KEY_K GLFW_KEY_K
#define KEYBOARD_KEY_L GLFW_KEY_L
#define KEYBOARD_KEY_M GLFW_KEY_M
#define KEYBOARD_KEY_N GLFW_KEY_N
#define KEYBOARD_KEY_O GLFW_KEY_O
#define KEYBOARD_KEY_P GLFW_KEY_P
#define KEYBOARD_KEY_Q GLFW_KEY_Q
#define KEYBOARD_KEY_R GLFW_KEY_R
#define KEYBOARD_KEY_S GLFW_KEY_S
#define KEYBOARD_KEY_T GLFW_KEY_T
#define KEYBOARD_KEY_U GLFW_KEY_U
#define KEYBOARD_KEY_V GLFW_KEY_V
#define KEYBOARD_KEY_W GLFW_KEY_W
#define KEYBOARD_KEY_X GLFW_KEY_X
#define KEYBOARD_KEY_Y GLFW_KEY_Y
#define KEYBOARD_KEY_Z GLFW_KEY_Z

#define KEYBOARD_KEY_ENTER GLFW_KEY_ENTER
#define KEYBOARD_KEY_BACKSPACE GLFW_KEY_BACKSPACE
#define KEYBOARD_KEY_ESCAPE GLFW_KEY_ESCAPE

#define KEYBOARD_KEY_ARROW_UP GLFW_KEY_UP
#define KEYBOARD_KEY_ARROW_DOWN GLFW_KEY_DOWN
#define KEYBOARD_KEY_ARROW_RIGHT GLFW_KEY_RIGHT
#define KEYBOARD_KEY_ARROW_LEFT GLFW_KEY_LEFT
