#pragma once

#include <Windows.h>
#include <GLFW/glfw3.h>

#define MOUSE_BUTTON_1 GLFW_MOUSE_BUTTON_1
#define MOUSE_BUTTON_2 GLFW_MOUSE_BUTTON_2
#define MOUSE_BUTTON_3 GLFW_MOUSE_BUTTON_3
#define MOUSE_BUTTON_4 GLFW_MOUSE_BUTTON_4
#define MOUSE_BUTTON_5 GLFW_MOUSE_BUTTON_5
#define MOUSE_BUTTON_6 GLFW_MOUSE_BUTTON_6
#define MOUSE_BUTTON_7 GLFW_MOUSE_BUTTON_7
#define MOUSE_BUTTON_8 GLFW_MOUSE_BUTTON_8

#define MOUSE_BUTTON_RIGHT GLFW_MOUSE_BUTTON_2
#define MOUSE_BUTTON_LEFT GLFW_MOUSE_BUTTON_1
#define MOUSE_BUTTON_MIDDLE GLFW_MOUSE_BUTTON_3
